# Fix64 v1.9.5 by @tbm00
# https://github.com/tbm00/Fix64/

### Prevents spawners from dropping exp when broken, thus disabling exp dupes (includes 1.21 trial spawners)
disableSpawnerEXP: true

### Prevents players from changing spawner mob types with spawn eggs
disableSpawnerConversion: true

### Prevents players from breaking trial spawners
disableTrialSpawnerBreak: true

### Prevents players from breaking vault blocks
disableVaultBreak: true

### Prevents players from placing redstone on trapdoors, thus minimizing light block dupes
fixLightTrapdoorDupe: true

### Prevents players from opening crafters with map inside, thus preventing client-crashing booby traps
fixCrafterMapCrash: true

### Prevents newbies (less than 4hr playtime) from using bundles (thus preventing 1.21.4 bundle crashes)
fixBundleCrash: true

### Disables bundles entirely (thus preventing 1.21.4 bundle dupes & crashes)
disableBundles: true

### Disables pistons from operating nearby tripwire & string, and prevents placement nearby one another (thus preventing some dupe methods)
disablePistonsNearTripwire: true

### Unloads all loaded chunks without nearby players on interval, thus minimizing chunk loaders
chunkUnloader:
  enabled: true
  timer: 480 # seconds
  radius: 16 # chunks around each player will not be unloaded

### Prevents entities from teleporting in portals, thus disabling some chunk loaders
enablePortalGaurd: true
bannedPortalEntities:
  - "BOAT"
  - "CHEST_BOAT"
  - "MINECART"
  - "MINECART_CHEST"
  - "MINECART_COMMAND"
  - "MINECART_FURNACE"
  - "MINECART_TNT"
  - "MINECART_HOPPER"
  - "MINECART_MOB_SPAWNER"
  - "DROPPED_ITEM"
  - "ITEM_DISPLAY"
  - "BLOCK_DISPLAY"
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html

### Prevents players from renaming items in anvils based on item's name & material
enableStopRenaming: true
banAllNames: false
bannedMaterials:
  - "TRIPWIRE_HOOK"
bannedNames:
  - "&4BadWord"