### BlockSpawnerEXP by SainttX
### https://www.spigotmc.org/threads/disable-xp-from-breaking-mob-spawners.19277/
enableBlockSpawnerEXP: true

### PortalGaurd by MetallicGoat
### https://github.com/MetallicGoat/PortalGaurd/
### Misspelling guard is by the original author
enablePortalGaurd: true
bannedPortalEntities:
  - "BOAT"
  - "CHEST_BOAT"
  - "MINECART"
  - "MINECART_CHEST"
  - "MINECART_COMMAND"
  - "MINECART_FURNACE"
  - "MINECART_TNT"
  - "MINECART_HOPPER"
  - "MINECART_MOB_SPAWNER"
  - "DROPPED_ITEM"
  - "ITEM_DISPLAY"
  - "BLOCK_DISPLAY"
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html

### StopRenaming by Xemor_
### https://www.spigotmc.org/resources/stoprenaming.80430/
enableStopRenaming: true
banAllNames: false
bannedMaterials:
  - TRIPWIRE_HOOK
bannedNames:
  - "&4BadWord"