### BlockSpawnerEXP by SainttX
### https://www.spigotmc.org/threads/disable-xp-from-breaking-mob-spawners.19277/



### PortalGuard by SainttX
### https://github.com/MetallicGoat/PortalGaurd/

# Entities blacklisted from using portals
# Possible values listed here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
bannedPortalEntities:
  - "ITEM"
  - "DISPLAY_ITEM"
  - "DISPLAY_BLOCK"
  - "DROPPED_ITEM"
  - "BOAT"
  - "CHEST_BOAT"
  - "MINECART"
  - "MINECART_CHEST"
  - "MINECART_COMMAND"
  - "MINECART_FURNACE"
  - "MINECART_TNT"
  - "MINECART_HOPPER"
  - "MINECART_MOB_SPAWNER"



### StopRenaming by Xemor_
### https://www.spigotmc.org/resources/stoprenaming.80430/
banAllNames: false
bannedMaterials:
  - TRIPWIRE_HOOK
bannedNames:
  - "&4BadWord"