### BlockSpawnerEXP by SainttX
### https://www.spigotmc.org/threads/disable-xp-from-breaking-mob-spawners.19277/

enbaleBlockSpawnerEXP: true


### PortalGaurd by SainttX
### https://github.com/MetallicGoat/PortalGaurd/
### Typo in guard is by the original author, lol

enbalePortalGaurd: true
bannedPortalEntities:
  - "BOAT"
  - "CHEST_BOAT"
  - "MINECART"
  - "MINECART_CHEST"
  - "MINECART_COMMAND"
  - "MINECART_FURNACE"
  - "MINECART_TNT"
  - "MINECART_HOPPER"
  - "MINECART_MOB_SPAWNER"
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html


### StopRenaming by Xemor_
### https://www.spigotmc.org/resources/stoprenaming.80430/

enbaleStopRenaming: true
banAllNames: false
bannedMaterials:
  - TRIPWIRE_HOOK
bannedNames:
  - "&4BadWord"