name: Fix64
version: ${project.version}
main: dev.tbm00.fix64.Fix64
api-version: 1.20
authors: [tbm00, SainttX, MetallicGoat, Xemor_]
description: This plugin allows you to stop certain items from being renamed
commands:
  fix64:
    description: the root command of this entire plugin
permissions:
  fix64.reload:
    description: Ability to use the reload command
    default: op
  fix64.eggconversion:
    description: Ability to convert spawners with spawn eggs
    default: op
  fix64.usebundles:
    description: Ability to use always use bundles
    default: op
  fix64.staff:
    description: Get staff/admin notifications
    default: op