name: Fix64
version: ${project.version}
main: dev.tbm00.fix64.Fix64
api-version: 1.13
authors: [tbm00, SainttX, MetallicGoat, Xemor_]
description: This plugin allows you to stop certain items from being renamed
commands:
  fix64:
    description: the root command of this entire plugin
    usage: /fix64 reload
permissions:
  fix64.reload:
    description: This permission gives you the ability to reload the config
    default: op